[package]
name = "nsfw-finder"
version = "0.1.0"
edition = "2021"

[dependencies]
camino = "1.1.7"
clap = { version = "4.5.15", features = ["derive"] }
color-eyre = "0.6.3"
image = "0.25.2"
nsfw = "0.2.0"
num_cpus = "1.16.0"
ordered-float = "4.2.2"
rayon = "1.10.0"
walkdir = "2.5.0"
